title: Built by Shawna
description: Personal coding projects landing pages and blog
baseurl: "" 
url: "https://builtbyshawna.dev"
theme: null

# Enable output for custom collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/
  books:
    output: true
    permalink: /books/:title/
  tooling:
    output: true
    permalink: /tooling/:title/

defaults:
  - scope:
      path: "_portfolio"
      type: "portfolio"
    values:
      layout: "section"
  - scope:
      path: "_books"
      type: "books"
    values:
      layout: "section"
  - scope:
      path: "_tooling"
      type: "tooling"
    values:
      layout: "section"

plugins:
  - jekyll-sitemap