title: Built by Shawna
description: Personal coding projects landing pages and blog
baseurl: "" 
url: "https://builtbyshawna.dev"

# Enable output for custom collections
collections:
  built:
    output: true
    permalink: /built/:title/
  read:
    output: true
    permalink: /read/:title/

defaults:
  - scope:
      path: "_built"
      type: "built"
    values:
      layout: "section"
  - scope:
      path: "_read"
      type: "read"
    values:
      layout: "section"
